+incdir+${OMC_DESIGN_ROOT}/

${OMC_DESIGN_ROOT}/oic_types.svh
${OMC_DESIGN_ROOT}/ORBIT_interface.svp
${OMC_DESIGN_ROOT}/orbit_payload_assign.svp
${OMC_DESIGN_ROOT}/CDAS_SingleDestPerID.svp
${OMC_DESIGN_ROOT}/WafterAW.svp
${OMC_DESIGN_ROOT}/RegisterSlice.svp
${OMC_DESIGN_ROOT}/lru_arbiter.svp
${OMC_DESIGN_ROOT}/ARAW_arbiter.svp
${OMC_DESIGN_ROOT}/ARAW_decoder.svp
${OMC_DESIGN_ROOT}/a_and_w_arbiter_nx1.svp
${OMC_DESIGN_ROOT}/a_and_w_decoder_1xn.svp
${OMC_DESIGN_ROOT}/r_and_b_arbiter_nx1.svp
${OMC_DESIGN_ROOT}/r_and_b_decoder_1xn.svp
${OMC_DESIGN_ROOT}/hxi_decoder_1xn.svp
${OMC_DESIGN_ROOT}/hxi_arbiter_nx1.svp
${OMC_DESIGN_ROOT}/bus_mux.svp
${OMC_DESIGN_ROOT}/oic_id_reducer.svp
${OMC_DESIGN_ROOT}/oic_ahb_to_ahb.svp
${OMC_DESIGN_ROOT}/oic_ahb_partial_chopper.svp
${OMC_DESIGN_ROOT}/oic_ahb_retry.svp
${OMC_DESIGN_ROOT}/oic_axi2ahb_core.svp
${OMC_DESIGN_ROOT}/oic_axi2ahb.svp
${OMC_DESIGN_ROOT}/oic_axi2ahb_lite.svp
${OMC_DESIGN_ROOT}/oic_ahb2axi.svp
${OMC_DESIGN_ROOT}/oic_ahb_lite2axi.svp
${OMC_DESIGN_ROOT}/oic_hxi2apb.svp
${OMC_DESIGN_ROOT}/oic_axi2apb.svp
${OMC_DESIGN_ROOT}/oic_apb2axi.svp
${OMC_DESIGN_ROOT}/oic_apb_async.svp
${OMC_DESIGN_ROOT}/oic_apb_tz_control.svp
${OMC_DESIGN_ROOT}/lda_dl_2x2_feedback.svp
${OMC_DESIGN_ROOT}/RS_AWRB.svp
${OMC_DESIGN_ROOT}/MO_counter.svp
${OMC_DESIGN_ROOT}/serdes.svp
${OMC_DESIGN_ROOT}/cg_unit.svp
${OMC_DESIGN_ROOT}/orbit_pmu.svp
${OMC_DESIGN_ROOT}/micro_pmu.svp
${OMC_DESIGN_ROOT}/qch_slave.svp
${OMC_DESIGN_ROOT}/micro_cmu.svp
${OMC_DESIGN_ROOT}/qos.svp
${OMC_DESIGN_ROOT}/latency_monitor_core.svp
${OMC_DESIGN_ROOT}/q_peak_latency_monitor.svp
${OMC_DESIGN_ROOT}/timeout_monitor_core.svp
${OMC_DESIGN_ROOT}/timeout_monitor.svp
${OMC_DESIGN_ROOT}/single_depth_fifo.svp
${OMC_DESIGN_ROOT}/ORBIT_IC_axi_to_hxi.svp
${OMC_DESIGN_ROOT}/oic_axi_dnsizer_req_ch.svp
${OMC_DESIGN_ROOT}/oic_axi_dnsizer_rdata_ch.svp
${OMC_DESIGN_ROOT}/oic_axi_dnsizer_wdata_ch.svp
${OMC_DESIGN_ROOT}/oic_axi_dnsizer_bresp_ch.svp
${OMC_DESIGN_ROOT}/oic_hxi_downsizer.svp
${OMC_DESIGN_ROOT}/oic_axi_upsizer_req_ch.svp
${OMC_DESIGN_ROOT}/oic_axi_upsizer_rdata_ch.svp
${OMC_DESIGN_ROOT}/oic_axi_upsizer_wdata_ch.svp
${OMC_DESIGN_ROOT}/oic_axi_upsizer_bresp_ch.svp
${OMC_DESIGN_ROOT}/oic_axi_upsizer_core.svp
${OMC_DESIGN_ROOT}/oic_axi_upsizer_top.svp
${OMC_DESIGN_ROOT}/oic_hxi_upsizer_req_ch.svp
${OMC_DESIGN_ROOT}/oic_hxi_upsizer_core.svp
${OMC_DESIGN_ROOT}/oic_hxi_upsizer_top.svp
${OMC_DESIGN_ROOT}/oic_hxi_upsizer_top.new.svp
${OMC_DESIGN_ROOT}/ORBIT_cr_hxi_if.svp
${OMC_DESIGN_ROOT}/cr_slave.svp
${OMC_DESIGN_ROOT}/HXI_flush.svp
${OMC_DESIGN_ROOT}/LPI_slave.svp
${OMC_DESIGN_ROOT}/lda_rs_unit.svp
${OMC_DESIGN_ROOT}/gray_counter.svp
${OMC_DESIGN_ROOT}/LDA_TX.svp
${OMC_DESIGN_ROOT}/LDA_RX.svp
${OMC_DESIGN_ROOT}/AsyncFIFO.svp
${OMC_DESIGN_ROOT}/oic_axi_async.svp
${OMC_DESIGN_ROOT}/lda_rs.svp
${OMC_DESIGN_ROOT}/lda_vc3in1.svp
${OMC_DESIGN_ROOT}/lda_si.svp
${OMC_DESIGN_ROOT}/lda_mi.svp
${OMC_DESIGN_ROOT}/lda_hxi_tx.svp
${OMC_DESIGN_ROOT}/lda_hxi_tl_tx.svp
${OMC_DESIGN_ROOT}/lda_hxi_rx.svp
${OMC_DESIGN_ROOT}/at_speed_test.svp
${OMC_DESIGN_ROOT}/hxi_default_slave.svp
${OMC_DESIGN_ROOT}/interrupt_register.svp
${OMC_DESIGN_ROOT}/hxi_bus_event_mon_cnt.svp
${OMC_DESIGN_ROOT}/evemon.svp
${OMC_DESIGN_ROOT}/fire_door.svp
${OMC_DESIGN_ROOT}/oic_secded_unit.svp
${OMC_DESIGN_ROOT}/oic_secded.svp
${OMC_DESIGN_ROOT}/sngl_slv.svp
${OMC_DESIGN_ROOT}/sngl_slv_id.svp
${OMC_DESIGN_ROOT}/ar_ch_1slv_top.svp
${OMC_DESIGN_ROOT}/ar_ch_1slv_top_with_chopper.svp
${OMC_DESIGN_ROOT}/ar_ch_1slv_id_top.svp
${OMC_DESIGN_ROOT}/ar_ch_1slv_id_top_with_chopper.svp
${OMC_DESIGN_ROOT}/aw_ch_1slv_top.svp
${OMC_DESIGN_ROOT}/aw_ch_1slv_top_with_chopper.svp
${OMC_DESIGN_ROOT}/aw_ch_1slv_id_top.svp
${OMC_DESIGN_ROOT}/aw_ch_1slv_id_top_with_chopper.svp
${OMC_DESIGN_ROOT}/req_chopper.svp
${OMC_DESIGN_ROOT}/ar_ch_cdas_bypass_top_with_chopper.svp
${OMC_DESIGN_ROOT}/r_ch_rlast_remover.svp
${OMC_DESIGN_ROOT}/aw_ch_cdas_bypass_top_with_chopper.svp
${OMC_DESIGN_ROOT}/b_ch_resp_merger.svp
${OMC_DESIGN_ROOT}/b_ch_resp_merger_with_rb.svp
${OMC_DESIGN_ROOT}/multi_destination_flag.svp
${OMC_DESIGN_ROOT}/oic_axi_req_reshaper.svp
${OMC_DESIGN_ROOT}/oic_axi_wdata_reshaper.svp
${OMC_DESIGN_ROOT}/oic_axi_reshaper.svp
${OMC_DESIGN_ROOT}/sram_model.svp
${OMC_DESIGN_ROOT}/simple_fifo.svp
${OMC_DESIGN_ROOT}/fifo_for_sync_clk.svp
${OMC_DESIGN_ROOT}/free_list_box.svp
${OMC_DESIGN_ROOT}/ar_ch_blk_gen.svp
${OMC_DESIGN_ROOT}/ar_ch_rb_core.svp
${OMC_DESIGN_ROOT}/ar_ch_rb_top.svp
${OMC_DESIGN_ROOT}/ar_ch_rb_top_with_chopper.svp
${OMC_DESIGN_ROOT}/s_node_ar_ch_rb_top_with_chopper.svp
${OMC_DESIGN_ROOT}/aw_ch_ex_blk_gen.svp
${OMC_DESIGN_ROOT}/aw_ch_rb_core.svp
${OMC_DESIGN_ROOT}/aw_ch_rb_top.svp
${OMC_DESIGN_ROOT}/aw_ch_rb_top_with_chopper.svp
${OMC_DESIGN_ROOT}/s_node_aw_ch_rb_top_with_chopper.svp
${OMC_DESIGN_ROOT}/r_ch_rb_core.svp
${OMC_DESIGN_ROOT}/r_ch_rb_top.svp
${OMC_DESIGN_ROOT}/skid_buffer_for_dual_spsram.svp
${OMC_DESIGN_ROOT}/r_ch_rb_core_with_multi_sram.svp
${OMC_DESIGN_ROOT}/r_ch_rb_core_with_multi_sram.dis_interleave.svp
${OMC_DESIGN_ROOT}/r_ch_exid_cnvtr.svp
${OMC_DESIGN_ROOT}/r_ch_rb_top_with_multi_sram.svp
${OMC_DESIGN_ROOT}/b_ch_rb_top.svp
${OMC_DESIGN_ROOT}/b_ch_exid_cnvtr.svp
${OMC_DESIGN_ROOT}/b_ch_rb_top_with_chopper.svp
${OMC_DESIGN_ROOT}/aw_w_sync_compact.svp
${OMC_DESIGN_ROOT}/c_node_qos_override_top.svp
${OMC_DESIGN_ROOT}/c_node_user_override_top.svp
${OMC_DESIGN_ROOT}/c_node_cr.svp
${OMC_DESIGN_ROOT}/c_node_cr_top.svp
${OMC_DESIGN_ROOT}/s_node_tzp.svp
${OMC_DESIGN_ROOT}/s_node_wid_generator.svp
${OMC_DESIGN_ROOT}/ar_ch_no_id_remap_with_chopper.svp
${OMC_DESIGN_ROOT}/aw_ch_no_id_remap_with_chopper.svp
${OMC_DESIGN_ROOT}/s_node_cr.svp
${OMC_DESIGN_ROOT}/s_node_cr_top.svp
${OMC_DESIGN_ROOT}/oic_axi_custom_bridge.svp
${OMC_DESIGN_ROOT}/oic_fpga_dbg.sv
${OMC_DESIGN_ROOT}/debug_info_string.svp
${OMC_DESIGN_ROOT}/oic_debug_utils.svp
${OMC_DESIGN_ROOT}/oic_axi_protocol_chk.svp
${OMC_DESIGN_ROOT}/omc_cfg.svp
${OMC_DESIGN_ROOT}/oic_sifive_sesame.svp
${OMC_DESIGN_ROOT}/dom_cog.svp
${OMC_DESIGN_ROOT}/addr_dec_dom_cog__cnd_axi_m0.svp
${OMC_DESIGN_ROOT}/route_info_dom_cog__cnd_axi_m0.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_m0_ar_top.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_m0_r_top.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_m0_aw_top.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_m0_w_top.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_m0_b_top.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_m0_core.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_m0_cg.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_m0_cg_addr_dec.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_m0.svp
${OMC_DESIGN_ROOT}/addr_dec_dom_cog__snd_axi_s0.svp
${OMC_DESIGN_ROOT}/route_info_dom_cog__snd_axi_s0.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_s0_define.svh
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_s0_addr_mgr.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_s0_ar_top.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_s0_r_top.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_s0_aw_top.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_s0_w_top.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_s0_b_top.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_s0_core.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_s0.svp
${OMC_DESIGN_ROOT}/addr_dec_dom_cog__cnd_axi_ctl.svp
${OMC_DESIGN_ROOT}/route_info_dom_cog__cnd_axi_ctl.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_ctl_ar_top.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_ctl_r_top.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_ctl_aw_top.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_ctl_w_top.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_ctl_b_top.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_ctl_core.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_ctl_cg.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_ctl_cg_addr_dec.svp
${OMC_DESIGN_ROOT}/dom_cog__cnd_axi_ctl.svp
${OMC_DESIGN_ROOT}/addr_dec_dom_cog__snd_axi_ctl.svp
${OMC_DESIGN_ROOT}/route_info_dom_cog__snd_axi_ctl.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_ctl_define.svh
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_ctl_addr_mgr.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_ctl_ar_top.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_ctl_r_top.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_ctl_aw_top.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_ctl_w_top.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_ctl_b_top.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_ctl_core.svp
${OMC_DESIGN_ROOT}/dom_cog__snd_axi_ctl.svp
${OMC_DESIGN_ROOT}/axi_pkg.svp
${OMC_DESIGN_ROOT}/omc_pkg.svp
${OMC_DESIGN_ROOT}/dfi_pkg.svp
${OMC_DESIGN_ROOT}/cr_pkg.svp
${OMC_DESIGN_ROOT}/dfi_if.svp
${OMC_DESIGN_ROOT}/cr_if.svp
${OMC_DESIGN_ROOT}/axi_if.svp
${OMC_DESIGN_ROOT}/maxi_if.svp
${OMC_DESIGN_ROOT}/scr_pkg.svp
${OMC_DESIGN_ROOT}/axi_scr_if.svp
${OMC_DESIGN_ROOT}/omc_reg_pkg.svp
${OMC_DESIGN_ROOT}/omc_secure_reg_pkg.svp
${OMC_DESIGN_ROOT}/omc_dfi_converter.svp
${OMC_DESIGN_ROOT}/omc_dfi_mesosync.svp
${OMC_DESIGN_ROOT}/omc_dfi_asyncfifo.svp
${OMC_DESIGN_ROOT}/omc_phyupd_mux.svp
${OMC_DESIGN_ROOT}/omc_train_en_ctrl.svp
${OMC_DESIGN_ROOT}/omc_asyncfifo.svp
${OMC_DESIGN_ROOT}/omc_axi_maxi.svp
${OMC_DESIGN_ROOT}/omc_oldest_selector.svp
${OMC_DESIGN_ROOT}/omc_page_table.svp
${OMC_DESIGN_ROOT}/omc_request_queue.svp
${OMC_DESIGN_ROOT}/omc_request_arbiter.svp
${OMC_DESIGN_ROOT}/omc_write_request_queue.svp
${OMC_DESIGN_ROOT}/omc_write_request_arbiter.svp
${OMC_DESIGN_ROOT}/omc_pclk_gate.svp
${OMC_DESIGN_ROOT}/omc_apb_sync.svp
${OMC_DESIGN_ROOT}/omc_control_interface.svp
${OMC_DESIGN_ROOT}/omc_apb_control.svp
${OMC_DESIGN_ROOT}/omc_apb_secure_control.svp
${OMC_DESIGN_ROOT}/omc_secure_cr.svp
${OMC_DESIGN_ROOT}/omc_nonsecure_cr.svp
${OMC_DESIGN_ROOT}/omc_bus_interface.svp
${OMC_DESIGN_ROOT}/omc_exclusive_monitor.svp
${OMC_DESIGN_ROOT}/omc_decoder.svp
${OMC_DESIGN_ROOT}/omc_asp_cr_async.svp
${OMC_DESIGN_ROOT}/omc_asp.svp
${OMC_DESIGN_ROOT}/omc_ecc_addr.svp
${OMC_DESIGN_ROOT}/omc_write_request_fifo.svp
${OMC_DESIGN_ROOT}/omc_wdq.svp
${OMC_DESIGN_ROOT}/omc_wch_fifo.svp
${OMC_DESIGN_ROOT}/omc_read_controller.svp
${OMC_DESIGN_ROOT}/omc_rdq.svp
${OMC_DESIGN_ROOT}/omc_qos.svp
${OMC_DESIGN_ROOT}/omc_axi_async.svp
${OMC_DESIGN_ROOT}/omc_axi_lda_tx.svp
${OMC_DESIGN_ROOT}/omc_axi_lda_rx.svp
${OMC_DESIGN_ROOT}/omc_axi_lda_rs.svp
${OMC_DESIGN_ROOT}/omc_axi_asyncfifo.svp
${OMC_DESIGN_ROOT}/omc_gray_counter.svp
${OMC_DESIGN_ROOT}/omc_scr_cr_async.svp
${OMC_DESIGN_ROOT}/omc_scr_addr.svp
${OMC_DESIGN_ROOT}/omc_scr_pipeline.svp
${OMC_DESIGN_ROOT}/omc_scr_key_rnd.svp
${OMC_DESIGN_ROOT}/omc_scr_data_rnd.svp
${OMC_DESIGN_ROOT}/omc_scr.svp
${OMC_DESIGN_ROOT}/omc_scr_enc.svp
${OMC_DESIGN_ROOT}/omc_scr_dec.svp
${OMC_DESIGN_ROOT}/omc_scr_addr_restore.svp
${OMC_DESIGN_ROOT}/omc_fsecc_addr.svp
${OMC_DESIGN_ROOT}/omc_fsecc.svp
${OMC_DESIGN_ROOT}/omc_fsecc_dec.svp
${OMC_DESIGN_ROOT}/omc_fsecc_dec_core.svp
${OMC_DESIGN_ROOT}/omc_fsecc_enc.svp
${OMC_DESIGN_ROOT}/omc_fsecc_enc_core.svp
${OMC_DESIGN_ROOT}/omc_fsecc_pb.svp
${OMC_DESIGN_ROOT}/omc_fsecc_pb_read_control.svp
${OMC_DESIGN_ROOT}/omc_fsecc_pb_write_control.svp
${OMC_DESIGN_ROOT}/omc_phy_interface.svp
${OMC_DESIGN_ROOT}/omc_phy_control_interface.svp
${OMC_DESIGN_ROOT}/omc_parity.svp
${OMC_DESIGN_ROOT}/omc_phy_cs_to_ca_latency.svp
${OMC_DESIGN_ROOT}/omc_phy_train_interface.svp
${OMC_DESIGN_ROOT}/omc_phy_write_controller.svp
${OMC_DESIGN_ROOT}/omc_phy_read_controller.svp
${OMC_DESIGN_ROOT}/omc_phy_retimer.svp
${OMC_DESIGN_ROOT}/omc_phy_lp_interface.svp
${OMC_DESIGN_ROOT}/omc_phy_upd_interface.svp
${OMC_DESIGN_ROOT}/omc_ecc_encode.svp
${OMC_DESIGN_ROOT}/omc_ecc_decode.svp
${OMC_DESIGN_ROOT}/omc_pwr_controller.svp
${OMC_DESIGN_ROOT}/omc_pwr_pch.svp
${OMC_DESIGN_ROOT}/omc_pwr_dfs.svp
${OMC_DESIGN_ROOT}/omc_pwr_rcg.svp
${OMC_DESIGN_ROOT}/omc_pwr_pwrmode.svp
${OMC_DESIGN_ROOT}/omc_device_monitor_bank.svp
${OMC_DESIGN_ROOT}/omc_device_monitor_rank.svp
${OMC_DESIGN_ROOT}/omc_device_monitor_rank_bank.svp
${OMC_DESIGN_ROOT}/omc_device_monitor.svp
${OMC_DESIGN_ROOT}/omc_scheduler.svp
${OMC_DESIGN_ROOT}/omc_scheduler_fsm.svp
${OMC_DESIGN_ROOT}/omc_monitor.svp
${OMC_DESIGN_ROOT}/omc_auto_refresh_controller.svp
${OMC_DESIGN_ROOT}/omc_sref_pwdn_controller.svp
${OMC_DESIGN_ROOT}/omc_sref_pwdn_controller_rank.svp
${OMC_DESIGN_ROOT}/omc_zq_calibrator.svp
${OMC_DESIGN_ROOT}/omc_page_policy_manager.svp
${OMC_DESIGN_ROOT}/omc_precharge_controller.svp
${OMC_DESIGN_ROOT}/omc_training_controller.svp
${OMC_DESIGN_ROOT}/omc_clk_controller.svp
${OMC_DESIGN_ROOT}/omc_mgr_req_arbiter.svp
${OMC_DESIGN_ROOT}/omc_core.svp
${OMC_DESIGN_ROOT}/omc_pwr_pd_ctrl_si.svp
${OMC_DESIGN_ROOT}/omc_pwr_pd_ctrl_mi.svp
${OMC_DESIGN_ROOT}/omc_secure_preproc_cr.svp
${OMC_DESIGN_ROOT}/omc_preproc_clk_controller.svp
${OMC_DESIGN_ROOT}/omc_preproc_core.svp
${OMC_DESIGN_ROOT}/omc.svp
${OMC_DESIGN_ROOT}/omc_wrapper.sv
${OMC_DESIGN_ROOT}/orbit_library.sv